-- Run this in Supabase SQL Editor.
-- Keep your existing access_keys, Deposit, Withdrawal and Users tables if already created.
-- This file adds the tables used by the online Admin/Sub Panel backend.

create table if not exists public.sub_panels (
  id bigint generated by default as identity primary key,
  name text not null,
  username text not null unique,
  password_hash text not null,
  active boolean not null default true,
  permissions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.user_locks (
  id bigint generated by default as identity primary key,
  uid text not null,
  reason text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_settings (
  key text primary key,
  value jsonb,
  updated_at timestamptz not null default now()
);

-- Backend uses the Supabase service-role key, so these tables can have RLS enabled.
alter table public.sub_panels enable row level security;
alter table public.user_locks enable row level security;
alter table public.admin_settings enable row level security;
