-- Run this in Supabase SQL Editor before using Sub Panel online.
create table if not exists public.sub_panels (
  id bigint generated by default as identity primary key,
  name text not null,
  username text not null unique,
  password_hash text not null,
  active boolean not null default true,
  permissions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Optional settings table for future online Customer Service configuration.
create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
